# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d52624df12f5f075cea1483af7b7ca387aa9424b79edab30ed1f7ade03c6a6079d91bea4c5df686a76844c5327f33b513e58d997d6d189134fe1e8502d7a7fd3

test:
  secret_key_base: fa6ef2f0a12676827cdd887886426b5045abc293aee309bdb9acde4877caa5ba32bee0c535c2ffa415c7d292afb0a960a4d20d438d6137dc0246ccb808a2e97c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
